### ISSUE TITLE
你好，看到你用flutter做的这个，对我要做的页面有一些帮助，有些问题想请教你一下

### ISSUE THREAD

**Issue by mxismean** [lwlizhe/flutter_tiktok#2]
可以留个联系方式， 我留意下我的微信：  m577956482

**Comment by mxismean** [comment]
NestedScrollerView 默认是只支持一个嵌套滚动， 我现在遇到的问题是想在  NestedScrollerView 中加两个同级的相互独立的滚动区域 类似于，饿了么的点餐，页面是一个大的滚动区域，头部是一个banner图，下面部分左右布局， 左边是可滚动的tab列表，右边是可滚动的tab对应的内容列表，左右两个相互独立，但是overscroll的时候都希望能自动触发外面滚动区域进行滚动。请教一下   望回复~   感谢

**Comment by lwlizhe** [comment]
额，我掘金有写过相关部分的[文章](https://juejin.im/post/5e1e80b55188253676295fe5)，可以看下，有啥不明白的直接评论就行了



掘金我还是上的蛮勤的……摸鱼必备网站之一……

这个项目……其实因为最近在学习openGL和ffmpeg，准备做那个相机模块，所以现在上的不是那么频繁……
